<?php /** @var $block \Magento\Framework\View\Element\Template */ ?>

<link rel="stylesheet" type="text/css" media="all" href="<?= $block->getViewFileUrl('Klevu_JSv2::css/klevu-landing.css'); ?>" />
<link rel="stylesheet" type="text/css" media="all" href="<?= $block->getViewFileUrl('Klevu_JSv2::css/klevu-landing-responsive.css'); ?>" />

<script type="text/javascript" src="<?= $block->getViewFileUrl('Klevu_JSv2::js/klevu-landing.js') ?>"></script>
