<?php /** @var $block \Magento\Framework\View\Element\Template */ ?>

<link rel="stylesheet" type="text/css" media="all" href="<?= $block->getViewFileUrl('Klevu_JSv2::css/klevu-quick.css'); ?>" />

<script type="text/javascript" src="//jsv2.klevu.com/export/klevu.js"></script>
<script type="text/javascript" src="<?= $block->getViewFileUrl('Klevu_JSv2::js/klevu-settings.js'); ?>"></script>
<script type="text/javascript" src="<?= $block->getViewFileUrl('Klevu_JSv2::js/klevu-quick.js'); ?>"></script>
