<?php /** @var $block \Magento\Framework\View\Element\Template */ ?>

<script type="text/javascript" src="<?= $block->getViewFileUrl('Klevu_JSv2::js/landing/klevu-landing.js') ?>"></script>

<link rel="stylesheet" type="text/css" media="all" href="<?= $block->getViewFileUrl('Klevu_JSv2::css/landing/klevu-landing.css'); ?>" />
<link rel="stylesheet" type="text/css" media="all" href="<?= $block->getViewFileUrl('Klevu_JSv2::css/landing/klevu-landing-responsive.css'); ?>" />
