<?php /** @var $block \Magento\Framework\View\Element\Template */ ?>

<script type="text/javascript" src="//js.klevu.com/klevu-js-v2/2.0/klevu.js"></script>
<script type="text/javascript" src="<?= $block->getViewFileUrl('Klevu_JSv2::js/klevu-settings.js'); ?>"></script>
<script type="text/javascript" src="<?= $block->getViewFileUrl('Klevu_JSv2::js/quick/klevu-quick.js'); ?>"></script>

<link rel="stylesheet" type="text/css" media="all" href="<?= $block->getViewFileUrl('Klevu_JSv2::css/quick/klevu-quick.css'); ?>" />
